# This file configures TEM and MADS parameters for STEP1 of the calibration 
# EJ 03/02/23
calib_mode: GPPAllIgnoringNitrogen
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
#- VegCarbon
#- VegStructuralNitrogen
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 13
PXx: 1
PXy: 0
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
- cmax
- cmax
- cmax
- cmax
- cmax  
pftnums:
- 0
- 1
- 2
- 3
- 4  
site: /data/input-catalog/caribou-poker
work_dir: /data/workflows/US-Prr-STEP1
mads_initial_guess:
- 460.0334580803363
- 319.8157
- 391.58212
- 158.3032
- 35.102473
mads_paramdist:
- Uniform(400, 470)
- Uniform(290, 330)
- Uniform(340, 385)
- Uniform(145, 175)
- Uniform(25, 50)
mads_paramkey:
- cmax0
- cmax1
- cmax2
- cmax3
- cmax4
mads_obsweight:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'OFF'
mads_obs_percent_variance: 1
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'ON'
mads_param_percent_variance: 20
mads_problemname: STEP1-USPrr-R-AM-v3
