# This file configures TEM and MADS parameters for STEP3 of the calibration 
# EJ 03/02/23
calib_mode: NPPVEGCVEGN
PXx: 1
PXy: 0

# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
- NPPAll
- VegCarbon
- VegStructuralNitrogen
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 13
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params: 
- nmax 
- nmax
- nmax
- nmax
- nmax
- krb(0)
- krb(0)
- krb(0)
- krb(0)
- krb(0)
- krb(1)
- krb(1)
- krb(2)
- krb(2)
- krb(2)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)  
- cfall(1)
- cfall(1)
- cfall(2)
- cfall(2)
- cfall(2)
- nfall(0)
- nfall(0)
- nfall(0)
- nfall(0)
- nfall(0)  
- nfall(1)
- nfall(1)
- nfall(2)
- nfall(2)
- nfall(2)
pftnums:
- 0
- 1
- 2
- 3
- 4  
- 0
- 1
- 2
- 3
- 4  
- 0
- 2
- 0
- 2
- 3
- 0
- 1
- 2
- 3
- 4  
- 0 
- 2
- 0
- 2
- 3
- 0
- 1
- 2
- 3
- 4  
- 0 
- 2
- 0
- 2
- 3
site: /data/input-catalog/caribou-poker
work_dir: /data/workflows/US-Prr-STEP3-SA-v2
mads_initial_guess:
- 9.03
- 5.22
- 5.23 
- 7.07
- 2.66  
- -9.611
- -2.295 
- -9.373 
- -19.9
- -3.400
- -7.70
- -19.93
- -3.51 
- -0.1
- -0.375
- 0.0018
- 0.065
- 0.074
- 0.014
- 0.0045
- 0.0033
- 0.004    
- 0.013
- 0.0029 
- 0.023
- 0.011
- 0.028
- 0.028
- 0.009 
- 0.001
- 0.001
- 0.006 
- 0.011
- 0.008
- 0.008
mads_paramdist:
- Uniform(4, 10)
- Uniform(1, 6)
- Uniform(1, 6)
- Uniform(2, 8)
- Uniform(1, 6) 
- Uniform(-10, -0.1)
- Uniform(-10, -0.1)
- Uniform(-10, -0.1)
- Uniform(-20, -0.1)
- Uniform(-10, -0.1)
- Uniform(-10, -0.1)
- Uniform(-20, -0.1)
- Uniform(-10, -0.1)
- Uniform(-10, -0.1)
- Uniform(-10, -0.1)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.2)
- Uniform(0.00001, 0.09)
- Uniform(0.00001, 0.09)
- Uniform(0.00001, 0.09)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.2)
- Uniform(1e-7, 0.09)
- Uniform(1e-7, 0.09)
- Uniform(1e-7, 0.09)
mads_paramkey:
- nmax0
- nmax1
- nmax2
- nmax3
- nmax4  
- krb00
- krb01
- krb02
- krb03
- krb04  
- krb10
- krb12
- krb20
- krb22
- krb23
- cfall00
- cfall01
- cfall02
- cfall03
- cfall04  
- cfall10
- cfall12
- cfall20
- cfall22
- cfall23
- nfall00
- nfall01
- nfall02
- nfall03
- nfall04  
- nfall10
- nfall12
- nfall20
- nfall22
- nfall23
mads_obsweight:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'ON'
mads_obs_percent_variance: 10
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'OFF'
mads_param_percent_variance: 70
mads_problemname: STEP3-US-Prr-R-AM-v2
