# This file configures TEM and MADS parameters for STEP4 of the calibration 
# EJ 03/02/23
calib_mode: VEGC
PXx: 1
PXy: 0
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
#- VegCarbon
#- VegStructuralNitrogen
#- MossDeathC
- CarbonShallow
- CarbonDeep
- CarbonMineralSum
- OrganicNitrogenSum
- AvailableNitrogenSum
cmtnum: 13
opt_run_setup: --pr-yrs 100 --eq-yrs 1000 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
- micbnup 
- kdcrawc 
- kdcsoma 
- kdcsompr
- kdcsomcr
pftnums:
- None
- None
- None
- None
- None
site: /data/input-catalog/caribou-poker
work_dir: /data/workflows/US-Prr-STEP4
mads_initial_guess:
- 1.202606  # micbnup: parameter for soil microbial immobialization of N  .64 
- 0.508619   # kdcrawc: raw-material (litter) C decompositin rates at reference condition   .654
- 0.234107    # kdcsoma:   0.58
- 0.002610   # kdcsompr:   
- 4.962393e-05 # kdcsomcr:
# NOTE: Kdcraw > Kdcactive > Kdcpr > Kdccr
mads_paramdist:
- Uniform(.5, 3)
- Uniform(0.12, 0.5)
- Uniform(0.008, 0.24)
- Uniform(0.0001, 0.007)
- Uniform(1e-11, 9e-5)
mads_paramkey:
- micbnup
- kdcrawc
- kdcsoma
- kdcsompr
- kdcsomcr
mads_obsweight:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'ON'
mads_obs_percent_variance: 10
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'ON'
mads_param_percent_variance: 30
mads_problemname: STEP4-US-Prr-R-AM
