# This file configures TEM and MADS parameters for STEP2 of the calibration 
# EJ 03/02/23
calib_mode: NPPVEGCVEGN
PXx: 0
PXy: 3
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
- VegCarbon
- VegStructuralNitrogen
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 14
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(1)
- cfall(1)
- cfall(1)
- cfall(1)
- cfall(2)
- cfall(2)
- cfall(2)
- cfall(2)
- nfall(0)
- nfall(0)
- nfall(0)
- nfall(0)
- nfall(0)
- nfall(1)
- nfall(1)
- nfall(1)
- nfall(1)
- nfall(2)
- nfall(2)
- nfall(2)
- nfall(2)

pftnums:
- 0
- 1
- 2
- 3
- 4  
- 0
- 1  
- 2
- 4  
- 0
- 1  
- 2
- 4
- 0
- 1
- 2
- 3
- 4
- 0
- 1
- 2
- 4
- 0
- 1
- 2
- 4

site: /data/input-catalog/caribou-poker
work_dir: /data/workflows/BONA-Birch-VegC-VegN-SA
mads_initial_guess:
- 0.0018       
- 0.0550       
- 0.0640       
- 0.0055
- 0.0550
- 0.0055       
- 0.0075       
- 0.0013       
- 0.0075
- 0.0070       
- 0.0085       
- 0.0012       
- 0.0085  
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005
- 0.005

mads_paramdist:
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.08)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)  
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)
- Uniform(0.001, 0.05)

mads_paramkey:
- cfall00
- cfall01
- cfall02
- cfall03
- cfall04
- cfall10
- cfall11
- cfall12
- cfall14
- cfall20
- cfall21
- cfall22
- cfall24
- nfall00
- nfall01
- nfall02
- nfall03
- nfall04
- nfall10
- nfall11
- nfall12
- nfall14
- nfall20
- nfall21
- nfall22
- nfall24

mads_obsweight:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'ON'
mads_obs_percent_variance: 20
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'ON'
mads_param_percent_variance: 70
mads_problemname: BONA-Birch-R-VegC-VegN-AM
