# This file configures TEM and MADS parameters for STEP3 of the calibration 
# EJ 03/02/23
calib_mode: NPPVEGC
PXx: 1
PXy: 0

# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
- VegCarbon
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 13
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params: 
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)  
- cfall(1)
- cfall(1)
- cfall(2)
- cfall(2)
- cfall(2)
pftnums:
- 0
- 1
- 2
- 3
- 4  
- 0 
- 2
- 0
- 2
- 3
site: /data/input-catalog/caribou-poker
work_dir: /data/workflows/US-Prr-STEP2-VEGC
mads_initial_guess:
- 0.004 
- 0.048342166
- 0.21442049
- 0.0001364299
- 0.048349
- 0.009138569
- 0.05536123
- 0.00880618
- 0.05233243
- 0.05119906
mads_paramdist:
- Uniform(0.0005, 0.01)
- Uniform(0.03, 0.06)
- Uniform(0.17, 0.23)
- Uniform(0.0001, 0.0008)
- Uniform(0.02, 0.06)
- Uniform(0.004, 0.01)
- Uniform(0.03, 0.07)
- Uniform(0.004, 0.01)
- Uniform(0.03, 0.06)
- Uniform(0.03, 0.06)

mads_paramkey:
- cfall00
- cfall01
- cfall02
- cfall03
- cfall04  
- cfall10
- cfall12
- cfall20
- cfall22
- cfall23

mads_obsweight:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'ON'
mads_obs_percent_variance: 10
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'OFF'
mads_param_percent_variance: 40
mads_problemname: STEP2-US-Prr-R-VEGC-AM
