# Example configuration file used to drive a sensitivity analysis.

# The location that is used to read all the initial parameter values.
seed_path: /work/parameters

# The path to the folder containing your calibration targets
# (calibration_targets.py) file
observations: /work/calibration

# The number of samples to draw over the parameter space
N_samples: 5

# The location where all the individual sample folders will be setup.
work_dir: /data/workflows/calibration/CMT06-IMNAVIAT/output/cmax_gppallignoringnitrogen/sa-N5

# The following keys (params, pftnums, and percent_diffs) should be lists of
# identical length. I.e. for each parameter we need to specify the PFT and a
# value for the perturbation. The perturbation is expressed as a percentage
# difference, and controls what kind of range is use to draw samples from for 
# the parameter.

# Which parameters are being tested/analyzed
params: [cmax, cmax, cmax, cmax, cmax, cmax, cmax]

# Which PFTs are being tested/analyzed
pftnums: [0, 1, 2, 3, 4, 5, 6]

# The "perturbations" around the initial parameter values
percent_diffs: [.1, .1, .1, .1, .1, .1, .1]

# Manually set parameter bounds. This option should be mutually exclusive 
# with percent_diffs. In other words only specify one of percent_diffs or 
# p_bounds. For each parameter specify the min and max. Must use square 
# brackets for yaml to parse it correctly.
#p_bounds: [[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]

# The path to the driving input data that will be used.
site: /data/input-catalog/cru-ts40_ar5_rcp85_ncar-ccsm4_IMNAVIAT_CREEK_10x10

# The pixel from the driving inputs that should be used.
PXx: 0
PXy: 0

# Control over which modules are turned on for which stage.
# The modes are:
#  - False/None/0: dvmdostem default which is dsl and nfeed on for eq, sp, tr, sc stages
#  - GPPALLIgnoringNitrogen: turns dsl and nfeed OFF for eq stage
#  - VEGC or NPPAll: turns dsl and nfeed ON for eq (and subsequent) stages
calib_mode: GPPAllIgnoringNitrogen

# What mathematical scheme to use to choose samples based on bounds, 
# and perturbations...
sampling_method: lhc

# The target variables that will be tested. Outputs are enabled based on 
# this setting...Note that here the names should match the names in the 
# calibration_targets.py file. Internally the program looks up the correct 
# NetCDF output to enable.
target_names: 
- GPPAllIgnoringNitrogen

# If you want additional outputs beyond the ones needed for the target
# comparison then you can specify them here. In this case use the NetCDF names.
# WARNING you should make sure that you don't explicity change the resolution
# for a variable that is one of your target variables. This will make the
# plotting in SA_post_hoc_analysis not work.
# aux_outputs:
# - VEGC p m
# - AVLN y
# - GPP y p c 
# - TLAYER m l

# The community number that is being calibrated.
cmtnum: 6

# Additional options that are passed to dvmdostem
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0


